### ISSUE TITLE
Move the Operator container image to `redhat-sap-cop` Org in Quay

### ISSUE THREAD

**Issue by makentenza** [redhat-sap/sap-commerce-operator#1]
Move the operator container image `quay.io/redhat-sap/hybris-operator:0.1` and any other custom container image specifically related to this operator under `redhat-sap-cop` Org

**Comment by makentenza** [comment]
@xieshenzh I'vecreated the Quay repo for this already and configure automatic builds for this. If we want to create a more complex CI for builds we can remove this automatic builds and create a GitHub workflow instead

https://quay.io/repository/redhat-sap-cop/hybris-operator

**Comment by xieshenzh** [comment]
Thanks @makentenza . 
We need to run command `make docker-build docker-push IMG=quay.io/redhat-sap-cop/hybris-operator:0.1` to build the operator. Using the `Dockerfile` alone won't work.
I'll create a GitHub workflow later and then let you know.

**Comment by makentenza** [comment]
Thanks @xieshenzh
