### ISSUE TITLE
 Change the load balancing type to ‘source’ 

### ISSUE THREAD

**Issue by tejones** [redhat-sap/sap-commerce-operator#14]
From customer email (Faizal)
The services are meant to load balance the request by default (roundrobin by default). Once the pods startup the application is considered to be available to use. In the case of Hybris though the application startup in Tomcat server takes much time to become online (even Hybris cluster shows up after few minutes).

Setting LB type to source will ensure the same client-ip will reach the same source pod always until the pod goes down.

**Comment by myeung18** [comment]
https://github.com/redhat-sap/sap-commerce-operator/pull/13
