### ISSUE TITLE
Add a readiness probe to the application deployment

### ISSUE THREAD

**Issue by tejones** [redhat-sap/sap-commerce-operator#15]
From customer email (Faizal)
The services are meant to load balance the request by default (roundrobin by default). Once the pods startup the application is considered to be available to use. In the case of Hybris though the application startup in Tomcat server takes much time to become online (even Hybris cluster shows up after few minutes).

Adding a readiness probe will make sure that pod starts entertaining requests only after it becomes ready from the application perspective

**Comment by myeung18** [comment]
https://github.com/redhat-sap/sap-commerce-operator/pull/13
