### ISSUE TITLE
During HybrisApp creation of services should expose 8009 as a NodePort service

### ISSUE THREAD

**Issue by faizalak** [redhat-sap/sap-commerce-operator#36]
HybrisApp today creates services automatically for 9001 and 9002. 8009 is an AJP port that is already having a listener from the Tomcat instance used in Hybris. This port 8009 needs to be exposed as a NodePort service for the user to consume the AJP endpoints. 

Need to add 8009 to the existing service (today has 9001 and 9002), change the type of the service to NodePort (today it is ClusterIP), and then have the user provide the specific nodePort value to use. A user entry is needed for nodePort since the port value needs to be static across multiple deployments. In the below example nodePort:30000 is a user-provided value

spec:
  clusterIP: 172.30.179.92
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ports:
    - name: 9001-http-tcp
      protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 30592
    - name: 9002-https-tcp
      protocol: TCP
      port: 9002
      targetPort: 9002
      nodePort: 32688
    - name: 8009-ajp-tcp
      protocol: TCP
      port: 8009
      targetPort: 8009
      nodePort: 30000
  clusterIPs:
    - 172.30.179.92
  type: NodePort
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: hybrisApp
    hybrisApp_cr: hybrisapp-sample-qa1

**Comment by tejones** [comment]
Done
